### ISSUE TITLE
Convert slides from xaringan to Quarto revealjs

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio-education/datascience-box#154]
Might also consider making code cells interactive with webR.

**Comment by mine-cetinkaya-rundel** [comment]
Useful tools:

- `knitr::convert_chunk_header()`
- Replace `---` with nothing with Ctrl+F (and then add them back just for the document YAML)

**Comment by tracykteal** [comment]
New YAML can be

```
---
title: "Title text!"
subtitle: "<br><br> Data Science in a Box"
author: "[datasciencebox.org](https://datasciencebox.org/)"
format:
  revealjs:
    css: ["../xaringan-themer.css", "../slides.css"]
    highlight-style: a11y
    slide-number: true
    footer: "https://datasciencebox.org"
---
```
